# Generated by Django 5.2.12 on 2026-09-27 02:59

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("certification_number", models.CharField(max_length=80, unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("license_plate", models.CharField(max_length=20)),
                ("make", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=80)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1886)]
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="fleet.office",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("maintenance_type", models.CharField(max_length=120)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="fleet.mechanic",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-maintenance_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("license_plate",),
                name="unique_active_vehicle_plate",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1886)), name="valid_vehicle_year"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["vehicle", "-maintenance_date"], name="vehicle_maintenance_date"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["mechanic", "maintenance_date"],
                name="mechanic_maintenance_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__gte", 0)),
                name="nonnegative_maintenance_cost",
            ),
        ),
    ]
